
package nl.hrlmr.complaint.service._1;

import javax.xml.ws.WebFault;

import nl.hrlmr.complaint.messages._1.UnknownComplaintFaultMessage;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebFault(name = "UnknownComplaintFaultMessage", targetNamespace = "http://hrlmr.nl/complaint/messages/1.0")
public class UnknownComplaintFault extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private UnknownComplaintFaultMessage faultInfo;

    /**
     *
     * @param message
     * @param faultInfo
     */
    public UnknownComplaintFault(String message, UnknownComplaintFaultMessage faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UnknownComplaintFault(String message, UnknownComplaintFaultMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: nl.hrlmr.complaint.messages._1.UnknownComplaintFaultMessage
     */
    public UnknownComplaintFaultMessage getFaultInfo() {
        return faultInfo;
    }

}
